    //Cop Shops
    class cop_pd {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_pd";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fnp45", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_FN57", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_smg_MP5N", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_M4A1_ris", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_bull", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_M4_ris_m", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_Black_60RndMag", "", 10, 0, "call life_coplevel >= 5" }
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_14Rnd_9x19_sw", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_20Rnd_57x28_SS190", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_30Rnd_9x19_B_MP5", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870_8Rnd_buck", "", 10, 0, "call life_coplevel >= 4" },
            { "CSW_M870_8Rnd_slug", "", 10, 0, "call life_coplevel >= 4" },
            { "CSW_M870_8Rnd_stun", "Gumowe Kule", 10, 0, "call life_coplevel >= 4" },
            { "RH_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_60Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_60rnd_Mk318_SOST_mag", "", 10, 0, "call life_coplevel >= 5" }   
        };
        accs[] = {
            { "RH_X300", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_flashlight_normal_2", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_compm4s", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_Hamr", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_6Rnd_454_Mag", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_spr_mbs", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_spr_mbs", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" },
            { "SCAR_10_Inches_Barrel_Silencer", "", 10, 0, "call life_coplevel >= 5" }
        };
    };
