    //Cop Shops
    class cop_pd {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_pd";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fnp45", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_FN57", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_smg_MP5N", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_M4A1_ris", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_bull", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_M4_ris_m", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_Black_60RndMag", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_m110", "", 10, 0, "call life_coplevel >= 5" },
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_14Rnd_9x19_sw", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_20Rnd_57x28_SS190", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_30Rnd_9x19_B_MP5", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870_8Rnd_buck", "", 10, 0, "call life_coplevel >= 4" },
            { "CSW_M870_8Rnd_slug", "", 10, 0, "call life_coplevel >= 4" },
            { "CSW_M870_8Rnd_stun", "Gumowe Kule", 10, 0, "call life_coplevel >= 4" },
            { "RH_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_60Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_60rnd_Mk318_SOST_mag", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_20Rnd_762x51_Mk316LR", "", 10, 0, "call life_coplevel >= 5" }
        };
        accs[] = {
            { "RH_X300", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_flashlight_normal_2", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_compm4s", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_Hamr", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_6Rnd_454_Mag", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_spr_mbs", "", 10, 0, "call life_coplevel >= 5" },
            { "SCAR_10_Inches_Barrel_Silencer", "", 10, 0, "call life_coplevel >= 5" },
            { "optic_AMS", "", 10, 0, "call life_coplevel >= 5" }
        };
    };

    class cop_so {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_so";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fnp45", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_FN57", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_smg_MP5N", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_M4A1_ris", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_bull", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_M4_ris_m", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_Black_60RndMag", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_m110", "", 10, 0, "call life_coplevel >= 5" },
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_14Rnd_9x19_sw", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_20Rnd_57x28_SS190", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_30Rnd_9x19_B_MP5", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870_8Rnd_buck", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870_8Rnd_slug", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_M870_8Rnd_stun", "Gumowe Kule", 10, 0, "call life_coplevel >= 3" },
            { "RH_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_60Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 5" },
            { "KA_SCAR_L_60rnd_Mk318_SOST_mag", "", 10, 0, "call life_coplevel >= 5" },
            { "RH_20Rnd_762x51_Mk316LR", "", 10, 0, "call life_coplevel >= 5" }
        };
        accs[] = {
            { "RH_X300", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_flashlight_normal_2", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_compm4s", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_Hamr", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_6Rnd_454_Mag", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_spr_mbs", "", 10, 0, "call life_coplevel >= 5" },
            { "SCAR_10_Inches_Barrel_Silencer", "", 10, 0, "call life_coplevel >= 5" },
            { "optic_AMS", "", 10, 0, "call life_coplevel >= 5" }
        };
    };

    class cop_swat {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_swat";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "Rangefinder", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizja", 10, 0, "call life_coplevel >= 1" },
            { "KA_M7290", "Granat Blyskowy", 2500, 0, "call life_coplevel >= 2" },
            { "KA_M7A30", "Gaz Lzawiacy", 2500, 0, "call life_coplevel >= 2" },
            { "KA_M814", "Granat EMP", 2500, 0, "call life_coplevel >= 2" },
            { "SmokeShellGreen", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShell", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShellRed", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShellYellow", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShellPurple", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShellBlue", "", 200, 0, "call life_coplevel >= 1" },
            { "SmokeShellOrange", "", 200, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fnp45", "", 15000, 0, "call life_coplevel >= 1" },
            { "RH_fnp45t", "", 18000, 0, "call life_coplevel >= 1" },,
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57_Ballistic_Shield", "FN57 Z Tarcza", 10, 0, "call life_coplevel >= 1" },
            { "hlc_rifle_bcmjack", "", 100, 0, "call life_coplevel >= 1" },
            { "SMA_M4MOE_SM", "", 100, 0, "call life_coplevel >= 1" },
            { "RH_M4A6", "", 100, 0, "call life_coplevel >= 2" },
            { "CSW_M870", "", 100, 0, "call life_coplevel >= 1" },
            { "RH_M16A6", "", 100, 0, "call life_coplevel >= 1" },
            { "RH_M27IAR", "", 100, 0, "call life_coplevel >= 1" },
            { "arifle_SDAR_F", "SDAR", 10, 0, "call life_coplevel >= 1" },
            { "RH_Hk416c", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_Hk416s", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_Hk416", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m110", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_SAMR", "", 10, 0, "call life_coplevel >= 2" },
            { "arifle_SPAR_03_blk_F", "", 10, 0, "call life_coplevel >= 3" },
            { "KA_CS5", "", 10, 0, "call life_coplevel >= 1" }
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_14Rnd_9x19_sw", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_20Rnd_57x28_SS190", "", 10, 0, "call life_coplevel >= 1" },
            { "hlc_30rnd_556x45_EPR", "", 10, 0, "call life_coplevel >= 1" },
            { "SMA_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_30Rnd_68x43_FMJ", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_M870_8Rnd_buck", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_M870_8Rnd_slug", "", 10, 0, "call life_coplevel >= 2" },
            { "CSW_M870_8Rnd_stun", "Gumowe Kule", 10, 0, "call life_coplevel >= 1" },
            { "RH_30Rnd_68x43_FMJ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_60Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 2" },
            { "20Rnd_556x45_UW_mag", "Podwodny magazynek", 10, 0, "call life_coplevel >= 2" },
            { "RH_20Rnd_762x51_Mk316LR", "", 10, 0, "call life_coplevel >= 3" }
            { "20Rnd_762x51_Mag", "", 10, 0, "call life_coplevel >= 2" },
            { "KA_CS5_10rnd_Mk316_SPR_mag", "", 10, 0, "call life_coplevel >= 3" },
            { "KA_CS5_10rnd_M948_SLAP_mag", "", 10, 0, "call life_coplevel >= 3" }
        };
        accs[] = {
            { "RH_suppr9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_X300", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_gemtech9", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_Arco", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_Arco_blk_F", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_AMS", "", 10, 0, "call life_coplevel >= 2" },
            { "optic_LRPS", "", 10, 0, "call life_coplevel >= 2" },
            { "optic_mrco", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_nightstalker", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_hamr", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_DMS", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_Holosight", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_eotech553mag", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AIM", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_SFM952V", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fa556", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_gemtech45", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_docter", "", 100, 0, "call life_coplevel >= 1" },
            { "RH_osprey", "", 10, 0, "call life_coplevel >= 1" },
            { "optic_MRD", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57_flashlight_normal_2", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_compm4s", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m110sd_t", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_TD_ACB", "", 10, 0, "call life_coplevel >= 1" },
            { "bipod_02_F_blk", "", 10, 0, "call life_coplevel >= 1" },
            { "muzzle_snds_B", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_CS5_Flashlight", "", 10, 0, "call life_coplevel >= 3" },
            { "KA_CS5_Silencer", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_silencer2", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_flashlight_normal_1", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_Barska", "", 10, 0, "call life_coplevel >= 3" },
            { "CSW_FN57_Shield_P", "", 10, 0, "call life_coplevel >= 3" },
            { "SMA_supp2b_556", "", 10, 0, "call life_coplevel >= 3" }
        };
    };

    class cop_dtu {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_dtu";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "Rangefinder", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizja", 10, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_tec9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fnp45", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fnp45t", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_Mk23_black", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_bullb", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_Deaglem", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_python", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_MP7_Pistol_Black_40Rnd", "", 100, 0, "call life_coplevel >= 3" },
            { "RH_python", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_FAMAS_F1", "", 10, 0, "call life_coplevel >= 3" },
            { "SMA_ACRREMMOECQBblk_N", "", 10, 0, "call life_coplevel >= 3" },
            { "SMA_HK416vfg", "", 10, 0, "call life_coplevel >= 3" },
            { "A3L_sign", "JP", 10, 0, "call life_coplevel >= 3" }
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_20Rnd_57x28_SS190", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_19Rnd_9x19_g18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_33Rnd_9x19_g18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_32Rnd_9x19_tec", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_12Rnd_45ACP_FMJ_Mag", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_7Rnd_50_AE", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_6Rnd_454_Mag", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_6Rnd_357_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_40Rnd_46x30_FMJ", "", 10, 0, "call life_coplevel >= 1" },
            { "SMA_ACRREMMOECQBblk_N", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_FAMAS_25rnd_SS109_FMJ_mag", "", 10, 0, "call life_coplevel >= 1" },
            { "SMA_30Rnd_556x45_M855A1", "", 10, 0, "call life_coplevel >= 1" }
        };
        accs[] = {
            { "RH_suppr9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_tecsd", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_x300", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_aacusp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_osprey", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_mrd", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_gemtech45", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57_silencer2", "", 10, 0, "call life_coplevel >= 1" },
            { "CSW_FN57_flashlight_normal_1", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9qd", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 1" },
            { "KA_Mk23_Flashlight", "", 10, 0, "call life_coplevel >= 2" },
            { "KA_Mk23_Silencer", "", 10, 0, "call life_coplevel >= 2" },
            { "optic_Yorris", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_demz", "", 10, 0, "call life_coplevel >= 2" },
            { "KA_MP7_Flashlight", "", 10, 0, "call life_coplevel >= 3" },
            { "RH_compM2", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_mrco", "", 10, 0, "call life_coplevel >= 2" },
            { "optic_hamr", "", 10, 0, "call life_coplevel >= 2" },
        };
    };
    
     class cop_aia {
        name = "Sklep Policyjny(Uzbrojenie)";
        side = "cop";
        conditions = "license_cop_aia";
        items[] = {
            { "Binocular", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemGPS", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemMap", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemCompass", "", 10, 0, "call life_coplevel >= 1" },
            { "ItemWatch", "", 10, 0, "call life_coplevel >= 1" },
            { "tf_anprc152", "Radio", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "Noktowizor", 10, 0, "call life_coplevel >= 1" },
            { "CG_BATON", "Palka Policyjna", 10, 0, "call life_coplevel >= 1" },
            { "CG_TELBAT", "Palka Teleskopowa", 10, 0, "call life_coplevel >= 1" },
            { "CSW_M26C", "Paralizator", 10, 0, "call life_coplevel >= 1" },
            { "NTRYK_Headset_NV", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_g18", "", 10, 0, "call life_coplevel >= 2" },
            { "RH_g19", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_m9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_cz75", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_p226", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_sw659", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_gsh18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_uspm", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_fn57", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_bull", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_smg_MP5N", "", 100, 0, "call life_coplevel >= 3" },
            { "hlc_rifle_samr2", "", 100, 0, "call life_coplevel >= 4" },
            { "SMG_01_F", "", 100, 0, "call life_coplevel >= 4" },
            { "RH_hb_b", "", 10, 0, "call life_coplevel >= 4" }
        };
        mags[] = {
            { "CSW_Taser_Probe_Mag", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_17Rnd_9x19_g17", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_19Rnd_9x19_g18", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_M9", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_9x19_CZ", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_9x19_SIG", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_14Rnd_9x19_sw", "", 10, 0, "call life_coplevel >= 1" },
            { "nonlethal_swing", "", 10, 0, "call life_coplevel >= 1" }
            { "RH_18Rnd_9x19_gsh", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_16Rnd_40cal_usp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_15Rnd_45cal_fnp", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_20Rnd_57x28_FN", "", 10, 0, "call life_coplevel >= 1" },
            { "RH_6Rnd_454_Mag", "", 10, 0, "call life_coplevel >= 3" },
            { "hlc_30Rnd_9x19_B_MP5", "", 10, 0, "call life_coplevel >= 4" },
            { "hlc_50rnd_556x45_EPR", "", 10, 0, "call life_coplevel >= 4" },
            { "30Rnd_556x45_Stanag", "", 10, 0, "call life_coplevel >= 4" },
            { "30Rnd_45ACP_Mag_SMG_01", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_30Rnd_762x35_FMJ", "", 10, 0, "call life_coplevel >= 4" }
        };
        accs[] = {
            { "RH_X300", "", 10, 0, "call life_coplevel >= 1" },
            { "FHQ_optic_AC11704", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_compm4s", "", 10, 0, "call life_coplevel >= 3" },
            { "optic_Hamr", "", 10, 0, "call life_coplevel >= 4" },
            { "RH_ta31rmr_2D", "", 10, 0, "call life_coplevel >= 4" }
        };
    };   
